export const SYSTEM_CONSTANTS = {
  BASE_URL: process.env.REACT_APP_API_URL,
  APP_NAME: process.env.REACT_APP_NAME,
  SORT_NAME: process.env.REACT_APP_SORTNAME,
  OKTA_ISSUER: process.env.REACT_OKTA_ISSUER,
  OKTA_CLIENTID: process.env.REACT_OKTA_CLIENTID,
};
